### ISSUE TITLE
hideflag "potion_effects" hides more than potion effects and should be renamed

### ISSUE THREAD

**Issue by ManInMyVan** [emanondev/ItemEdit#11]

**Comment by emanondev** [comment]
it has this name for historical reasons, it is also a reference to existing ItemFlag https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/inventory/ItemFlag.html#HIDE_POTION_EFFECTS

however it's name could be changed anytime inside aliases folder

**Comment by ManInMyVan** [comment]
What is ae_glow and glowing_enchant?

**Comment by emanondev** [comment]
those are custom enchants added by other plugins, i suppose their purpose is to add glowing effect without adding any enchantment behavior
