### ISSUE TITLE
[Suggestion] Add support for AdvancedEnchantments 

### ISSUE THREAD

**Issue by NoltoxGit** [emanondev/ItemEdit#16]
Hi,
Would it be possible to add support for AdvancedEnchantments plugin [(API HERE)](https://ae.advancedplugins.net/for-developers/plugin-api) with their custom enchantements please ?

Thank you very much !
~ Noltox ~

**Comment by emanondev** [comment]
Provided api it's not sufficient to add a decent support, also premium plugin makes impossible to make any test, sorry
