### ISSUE TITLE
Commands `/si show` and `/si give` give different items when used.

### ISSUE THREAD

**Issue by BCMonomial** [emanondev/ItemEdit#20]
When accessing an uploaded server item (with custom lore and NBT made by ItemEdit), the two commands mentioned give two different items with different NBTs, making them unstackable or not tradable.

Tried `/si update`, but the issue persisted. Below is an example of what happened.

![2024-01-21 16-10-51_2](https://github.com/emanondev/ItemEdit/assets/69715347/335ea849-362f-4a53-9be5-535edd94a5d9)

**Comment by BCMonomial** [comment]
The server is running on Pufferfish 1.20.4, ItemEdit version being the latest 3.1.6.

**Comment by BCMonomial** [comment]
Update: After some investigation, we figured that this bug is most probably caused by the update from older Minecraft version to 1.20.3+, which applys a stricter rule for item NBTs when an item is created, but existing items are not affected. 

I'm not a professional in codes so I can only make wild guesses. I guess that these two commands are using different methods to create items, with one being an exact copy of registered item, and another calling an in-game API to go through the normal item creation process. This difference caused the items to be different.

Again this is only a guess and I haven't read / don't have the ability to understand the source code of ItemEdit, so I might be wrong.

**Comment by emanondev** [comment]
Sorry, i took a lot of time trying to replicate the bug but wans't able to

However i believe i did understand how the issue works, it is related to chat components as you said, as on /si give the plugin try to replace any placeholders (from PlaceholderAPI) on the name and lore, that attemp shoudn't change anything on view side if there are no placeholders but may still change how the ChatComponents are set, on /si show you just get a clone of the item with placeholders untouched and same for ChatComponents

- If you do not use PlaceholderAPI feature on ItemEdit items i believe this issue should be solved by turning to false on config.yml this:
```
serveritem:
  replace-holders: false
```

- You should also be able to fix that issue by using /si update \<id\> with the item obtained from /si give \<id\>, it's a bit more work to do than previous solution to do but doesn't require to give up to placeholders feature

If none of these solve your issue feel free to reopen this thread

(Maybe i can also add a way to understand if any placeholders are replaced on name/lore and avoid changing the item meta if none are meet)
