### ISSUE TITLE
Error.

### ISSUE THREAD

**Issue by KhrysAK47** [emanondev/ItemEdit#22]
I have updated from Paper 1.19.4 to 1.20.4 and now giving items has this error.

https://pastebin.com/9WD9TkGL

**Comment by emanondev** [comment]
Thanks for the report! it should be solved now

**Comment by KhrysAK47** [comment]
> Thanks for the report! it should be solved now

Just to confirm - it will not mess up any nbt related stuff if I update with the fix?

**Comment by emanondev** [comment]
no, the plugin do not touch nbt stuff
