### ISSUE TITLE
ItemEdit v3.5.2 - MC v1.21.3

### ISSUE THREAD

**Issue by EHCanadian** [emanondev/ItemEdit#27]
CraftBukkit version 4361-Spigot-5eb8a94-6029040 (MC: 1.21.3)

`
[Server thread/INFO]: [ItemEdit] Enabling ItemEdit v3.5.2
[Server thread/INFO]: [0;34;22m[[0;37;1mItemEdit[0;34;22m] [0;37;1m[0;31;1mError while loading ItemEdit, disabling it[m
[Server thread/WARN]: java.lang.ClassCastException: interface org.bukkit.attribute.Attribute not an enum
[Server thread/WARN]: 	at java.base/java.util.EnumSet.noneOf(EnumSet.java:115)
[Server thread/WARN]: 	at java.base/java.util.EnumSet.allOf(EnumSet.java:134)
[Server thread/WARN]: 	at emanondev.itemedit.aliases.EnumAliasSet.getValues(EnumAliasSet.java:27)
[Server thread/WARN]: 	at emanondev.itemedit.aliases.AliasSet.reload(AliasSet.java:24)
[Server thread/WARN]: 	at emanondev.itemedit.aliases.Aliases.reload(Aliases.java:165)
[Server thread/WARN]: 	at emanondev.itemedit.ItemEdit.enable(ItemEdit.java:82)
[Server thread/WARN]: 	at emanondev.itemedit.APlugin.onEnable(APlugin.java:215)
[Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:267)
[Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342)
[Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:492)
[Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_21_R2.CraftServer.enablePlugin(CraftServer.java:579)
[Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_21_R2.CraftServer.enablePlugins(CraftServer.java:493)
[Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:656)
[Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:441)
[Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:268)
[Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1032)
[Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329)
[Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1575)
[Server thread/INFO]: [ItemEdit] Disabling ItemEdit v3.5.2

`

**Comment by emanondev** [comment]
should be fixed with last changes, please come to discord to test the new version or wait until i put it on spigot

thanks for the report
