### ISSUE TITLE
Modrinth and/or GitHub releases

### ISSUE THREAD

**Issue by Folas1337** [emanondev/ItemEdit#28]
I just thought it might be worth asking for releases on GitHub and/or Modrinth as I prefer those platforms to grab my plugins :)

The main reason being that each update gives me a notification that I can confirm per release rather than how it's done on spigot where it's just a notification which you can't actively confirm after you updated. 

It could also help in getting more people to find this plugin.

**Comment by emanondev** [comment]
done, we need to wait for resource approval within 48h usually, then the link should be https://modrinth.com/plugin/itemedit

**Comment by Folas1337** [comment]
Thanks a lot, I greatly appreciate the effort <3
