### ISSUE TITLE
[Request] Use tab complete for /ie lore set <no>

### ISSUE THREAD

**Issue by TomLewis** [emanondev/ItemEdit#3]
When editing an existing lore from an item, please auto fill whats already on the item, so we can easily make changes to existing text/lore without having to re-make the lore line (if were in a differnt session or another user editing)

Also I think theres a bug with the tab complete when setting the lore line number, it only shows 1, 3 and 10 as options for lore line number for the item im holding, which is odd, if this could be fixed to be dynamic to be based off the amount of lore lines the currently held item has.

**Comment by emanondev** [comment]
sure, i can fix the tab complete and yes 1, 3, 10 were fixed numbers, i can change that too (however lore set is not limited to replace, it also adds empty lines if your line is greater than current biggest line)

**Comment by TomLewis** [comment]
Sounds good! Thanks!
