### ISSUE TITLE
[Suggestion] Add an option to disable item drop to the ground when inventory is full

### ISSUE THREAD

**Issue by kolderz** [emanondev/ItemEdit#9]
Thanks for the fantastic plugin. Can you add an option to disable item drop to the ground when inventory is full when using the ``serveritem give`` command?

**Comment by emanondev** [comment]
ok, so should i delete them?

**Comment by clarkkentz** [comment]
> ok, so should i delete them?
> 
> should i also tell to the player that he was unable to get them all? should i tell to the user which used /si give or /si giveall that player was unable to get them?

That could work or maybe an option to toggle this feature?

**Comment by emanondev** [comment]
sorry it took very long (i forgot of this) you can now change give behavior on config.yml
```
serveritem: 
  give-drops-excess: true/false
```
